#!/bin/bash

# broadcast address
brd=""

while read line
do
  if [ "$1" == "$(echo $line | sed 's/\=.*$//g')" ];then
        MACADDRESS=$(echo $line | sed 's/^.*\=//g')
        wakeonlan -i $brd $MACADDRESS
        exit 1
  fi
done < $HOME/etc/macaddress

if [ $? == "1"]; then exit; fi
echo 'Server is not found. Please check ~/etc/macaddress.'
echo 'This command is located at ~/bin/wol.'
